Update run_modal.py
(this is my first commit. hope i did it right.)

1. use different modal image because of 
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
https://modallabscommunity.slack.com/archives/C06GPR10K9V/p1727974576549739?thread_ts=1727846442.111349&cid=C06GPR10K9V

2. fix modal 504 error by excluding venv and __pycache__ folders from being uploaded to modal.

3. optional: pass huggingface token